export const ADD_INGRATIENT = 'ADD_INGRATIENT';
export const REMOVE_INGRATIENT = 'REMOVE_INGRATIENT';
export const UPDATE_PURCHASEABLE = 'UPDATE_PURCHASEABLE';
export const RESET_INGRATIENT = 'RESET_INGRATIENT';

// fetch data
export const LOAD_ORDERS = 'LOAD_ORDERS';
export const ORDERS_LOAD_FAILED = 'ORDERS_LOAD_FAILED';

// login & sign up

export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILED = 'AUTH_FAILED';
export const AUTH_LOADING = 'AUTH_LOADING';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';